# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python:
  - "3.5"

install:
  - pip install tox
  - "TOX_ENV=${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}"
script: tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
