# Config file for automatic testing at travis-ci.org
language: minimal
sudo: required 
matrix:
  include:
  - os: linux
    dist: xenial
    env: [P=2, p=7]
  - os: linux
    dist: xenial
    env: [P=3, p=5]
  - os: linux
    dist: bionic
    env: [P=3, p=6]
  - os: linux
    dist: bionic
    env: [P=3, p=7]

install:
  - sudo apt-get update -y
  - sudo apt-get install -y python${P}.${p}-dbg
  - virtualenv --python=python${P}.${p}-dbg env
  - source env/bin/activate
  - pip install tox

script:
  - tox -e python${P}.${p}-dbg
  - 'if [ "${P}" = "3" ]; then tox -e python${P}-dbg-pytest3,python${P}-dbg-pytest4,python${P}-dbg-pytest5; fi'
before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
