# Config file for automatic testing at travis-ci.org

language: generic
dist: bionic
sudo: required 
# addons:
#   apt:
#     packages:
#       - python2.7-dbg
#       - python3.5-dbg
#       - python3.6-dbg
#       - python3.7-dbg

install:
  - sudo apt-get update -y
  - sudo apt-get install -y python3.6-dbg python3.7-dbg
  - virtualenv --python=python3.6-dbg env
  - source env/bin/activate
  - pip install tox

script:
  - tox

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
