# Config file for automatic testing at travis-ci.org
language: minimal
sudo: required 
matrix:
  include:
  - os: linux
    dist: xenial
    env: PY=2.7
  - os: linux
    dist: xenial
    env: PY=3.5
  - os: linux
    dist: bionic
    env: PY=3.6
  - os: linux
    dist: bionic
    env: PY=3.7

install:
  - sudo apt-get update -y
  - sudo apt-get install -y python${PY}-dbg
  - virtualenv --python=python${PY}-dbg env
  - source env/bin/activate
  - pip install tox

script:
  - tox -e python${PY}-dbg

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
