# Config file for automatic testing at travis-ci.org

language: generic
dist: bionic
addons:
  apt:
    packages:
      - python2.7-dbg
      - python3.5-dbg
      - python3.6-dbg
      - python3.7-dbg

install:
  - virtualenv --python=python3.5-dbg env
  - source env/bin/activate
  - pip install tox

script:
  - tox

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
