# Config file for automatic testing at travis-ci.org
language: minimal
sudo: required 
matrix:
  include:
  - os: linux
    dist: xenial
    env: [PYVER=2.7]
  - os: linux
    dist: xenial
    env: [PYVER=3.5]
  - os: linux
    dist: bionic
    env: [PYVER=3.6]
  - os: linux
    dist: bionic
    env: [PYVER=3.7]

install:
  - sudo apt-get update -y
  - sudo apt-get install -y python${PYVER}-dbg
  - virtualenv --python=python${PYVER}-dbg env
  - source env/bin/activate
  - pip install tox

script:
  - |
    if [ "${PYVER}" = "2.7" ]; then
       ENVS=python${PYVER}-dbg
    elif [ "${PYVER}" = "3.5" ]; then
       ENVS=python${PYVER}-dbg,python3-dbg-pytest3,python3-dbg-pytest4
    else
       ENVS=python${PYVER}-dbg,python3-dbg-pytest3,python3-dbg-pytest4,python3-dbg-pytest5
    fi
  - tox -e "$ENVS"

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
